# Generated by Django 4.0.4 on 2022-05-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_hospital_subject_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reservations',
            field=models.ManyToManyField(related_name='user_reservation', through='reservations.Reservation', to='users.doctor'),
        ),
    ]
