# Generated by Django 4.0.4 on 2022-06-07 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subject_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='working_times',
        ),
        migrations.CreateModel(
            name='DoctorTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=20)),
                ('times', models.CharField(max_length=500)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_time', to='users.doctor')),
            ],
            options={
                'db_table': 'doctor_times',
            },
        ),
    ]
