# Generated by Django 4.0.4 on 2022-06-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_doctor_working_times_doctortime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='working_days',
        ),
        migrations.CreateModel(
            name='DoctorDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearmonth', models.CharField(max_length=20)),
                ('days', models.CharField(max_length=500)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_day', to='users.doctor')),
            ],
            options={
                'db_table': 'doctor_days',
            },
        ),
    ]
