# Generated by Django 4.0.4 on 2022-06-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_doctor_working_days_doctorday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorday',
            name='yearmonth',
        ),
        migrations.AddField(
            model_name='doctorday',
            name='month',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorday',
            name='year',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
