# Generated by Django 4.0.4 on 2022-06-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
    ]
